spring:
  datasource:
    url: jdbc:mysql://uproad-1.c3zbqtbixzbk.ap-northeast-2.rds.amazonaws.com:3306/store
    username: admin
    password: comet2059!
    hikari:
      minimum-idle: 1
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
logging:
  file:
    name: log/store.log
    max-size: 10MB
    max-history: 1000
  level:
    sql: debug
  debug: true
jwt:
  header: Authorization
  secret: LPEAERK0617SBOYNEGONG1217YYIUN
  token-validity-in-seconds: 3600000
server:
  port: 8080 # set port to 5000 for serve on AWS
